import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { CATALOGUE } from '../../ui/src/catalogue.ts';
import { elementsDoc } from '../../../scripts/docs-elements.ts';

/**
 * The catalogue's reference cannot fall behind the catalogue
 * (`tasks/apps` A9-F03-TC002).
 *
 * `docs/elements.md` is generated by `bun run docs:elements`. This builds the
 * same text and holds the file to it, so an element or a setting added to
 * `@brydio/ui` without regenerating fails here — nobody has to remember. Any
 * document a person has to remember to update is already out of date.
 */

const root = join(import.meta.dir, '../../..');
const onDisk = () => readFileSync(join(root, 'docs', 'elements.md'), 'utf8');

describe('the catalogue reference', () => {
  test('is what the catalogue says, to the character', () => {
    expect(onDisk().trim()).toBe(elementsDoc().trim());
  });

  test('has a section and a settings table for every element', () => {
    const page = onDisk();
    const names = Object.keys(CATALOGUE);

    expect(names.length).toBeGreaterThan(20);

    for (const name of names) {
      expect(page, `${name} has no section`).toContain(`## \`${name}\``);

      for (const setting of Object.keys((CATALOGUE as Record<string, { props: object }>)[name]!.props)) {
        // The setting's own row, not merely the word somewhere on the page.
        expect(page, `${name} does not document ${setting}`).toContain(`| \`${setting}\` |`);
      }
    }
  });

  test('says which settings an element cannot be drawn without', () => {
    // `bry-heading` needs its text; a page that lost "Needed" would still
    // list every setting and still be wrong about how to use one.
    const heading = onDisk().split('## `bry-heading`')[1]!.split('## `')[0]!;

    expect(heading).toContain('| `text` | text, at most 200 characters | yes |');
    expect(heading).toContain('| `level` | a whole number from 1 to 4 | no |');
  });

  test('says what an element tells the app, and what holds children', () => {
    const page = onDisk();
    const button = page.split('## `bry-button`')[1]!.split('## `')[0]!;
    const stack = page.split('## `bry-stack`')[1]!.split('## `')[0]!;

    expect(button).toContain('`press`');
    expect(stack).toContain('Holds other elements or text.');
    expect(button).toContain('Holds nothing');
  });

  test('is named by the README, so a builder can find it', () => {
    expect(readFileSync(join(root, 'README.md'), 'utf8')).toContain('(docs/elements.md)');
  });
});
