import { createHash } from 'node:crypto';

import type { ElementName } from '../../packages/ui/src/catalogue.ts';

export interface ExampleNode {
  id: string;
  type: ElementName;
  props: Record<string, unknown>;
  children?: string[];
}

export interface ElementExample {
  about: string;
  root: string;
  nodes: ExampleNode[];
}

const one = (about: string, node: ExampleNode, more: ExampleNode[] = []): ElementExample => ({
  about,
  root: node.id,
  nodes: [node, ...more],
});

const ISSUES = ['Crash on save', 'Search ignores accents', 'Dark mode flickers'];

export const EXAMPLES = {
  'bry-stack': one('A row or column with a gap.', { id: 'stack', type: 'bry-stack', props: { direction: 'row', gap: '2', align: 'center' }, children: ['todo', 'doing', 'done'] }, [
    { id: 'todo', type: 'bry-badge', props: { text: 'To do' } },
    { id: 'doing', type: 'bry-badge', props: { text: 'Doing', tone: 'brand' } },
    { id: 'done', type: 'bry-badge', props: { text: 'Done', tone: 'success' } },
  ]),
  'bry-heading': one('A heading in the document outline.', { id: 'heading', type: 'bry-heading', props: { level: 2, text: 'Issues' } }),
  'bry-text': one('Body text with a muted detail.', { id: 'text-stack', type: 'bry-stack', props: { gap: '1' }, children: ['body', 'detail'] }, [
    { id: 'body', type: 'bry-text', props: { text: 'Three issues are open this week.' } },
    { id: 'detail', type: 'bry-text', props: { text: 'Updated a minute ago', tone: 'muted', size: 'sm' } },
  ]),
  'bry-button': one('An action button.', { id: 'button', type: 'bry-button', props: { label: 'New issue', variant: 'primary', icon: 'add' } }),
  'bry-card': one('A titled card with content.', { id: 'card', type: 'bry-card', props: { title: ISSUES[0], padding: '3', pressable: true }, children: ['card-text'] }, [
    { id: 'card-text', type: 'bry-text', props: { text: 'Opened by Ada', tone: 'muted', size: 'sm' } },
  ]),
  'bry-input': one('A one-line input.', { id: 'input', type: 'bry-input', props: { label: 'Title', value: ISSUES[0] } }),
  'bry-textarea': one('A multi-line input.', { id: 'textarea', type: 'bry-textarea', props: { label: 'Body', placeholder: 'Steps to reproduce' } }),
  'bry-select': one('A short list of choices.', { id: 'select', type: 'bry-select', props: { label: 'Status', value: 'doing', options: [{ value: 'todo', label: 'To do' }, { value: 'doing', label: 'Doing' }, { value: 'done', label: 'Done' }] } }),
  'bry-label': one('A field label and its control.', { id: 'label', type: 'bry-label', props: { text: 'Title', required: true }, children: ['label-input'] }, [
    { id: 'label-input', type: 'bry-input', props: { placeholder: 'What went wrong?' } },
  ]),
  'bry-grid': one('Equal columns that respond to available width.', { id: 'grid', type: 'bry-grid', props: { columns: '3', gap: '3' }, children: ['grid-1', 'grid-2', 'grid-3'] }, [
    ...['To do', 'Doing', 'Done'].map((title, index) => ({ id: `grid-${index + 1}`, type: 'bry-card' as const, props: { title, padding: '3' } })),
  ]),
  'bry-badge': one('A compact status.', { id: 'badge', type: 'bry-badge', props: { text: 'In progress', tone: 'brand' } }),
  'bry-avatar': one('A person represented by initials.', { id: 'avatar', type: 'bry-avatar', props: { name: 'Ada Lovelace', size: 'lg' } }),
  'bry-list-row': one('A row in a list.', { id: 'list-row', type: 'bry-list-row', props: { title: ISSUES[0], description: 'Opened by Ada', meta: '2d', pressable: true, selected: true }, children: ['row-badge'] }, [
    { id: 'row-badge', type: 'bry-badge', props: { text: 'Bug', tone: 'danger' } },
  ]),
  'bry-empty-state': one('A view with nothing to show yet.', { id: 'empty-state', type: 'bry-empty-state', props: { title: 'No issues yet', text: 'Issues you make show up here.', action: 'New issue' } }),
  'bry-skeleton': one('A loading placeholder.', { id: 'skeleton', type: 'bry-skeleton', props: { shape: 'row', count: 3 } }),
  'bry-table': one('Rows and sortable columns.', { id: 'table', type: 'bry-table', props: { label: 'Issues', columns: [{ key: 'title', heading: 'Title', sortable: true }, { key: 'status', heading: 'Status' }], rows: [{ id: '1', cells: [ISSUES[0], 'To do'] }, { id: '2', cells: [ISSUES[1], 'Doing'] }], selectable: true, selected: '2' } }),
  'bry-virtual-list': one('A long list drawn in a window.', { id: 'virtual-list', type: 'bry-virtual-list', props: { label: 'All issues', count: 3, start: 0, rowSize: 'md' }, children: ['virtual-1', 'virtual-2', 'virtual-3'] }, [
    ...ISSUES.map((title, index) => ({ id: `virtual-${index + 1}`, type: 'bry-list-row' as const, props: { title } })),
  ]),
  'bry-dialog': one('A question requiring an answer.', { id: 'dialog', type: 'bry-dialog', props: { open: false, title: 'Delete this issue?', description: 'Its comments go with it.', actions: [{ id: 'delete', label: 'Delete', tone: 'danger' }] } }),
  'bry-menu': one('A short list of actions.', { id: 'menu', type: 'bry-menu', props: { items: [{ id: 'archive', label: 'Archive', icon: 'archive' }, { id: 'delete', label: 'Delete', tone: 'danger', separator: true }] }, children: ['menu-button'] }, [
    { id: 'menu-button', type: 'bry-button', props: { label: 'More', variant: 'secondary', size: 'sm' } },
  ]),
  'bry-date': one('A date from a calendar.', { id: 'date', type: 'bry-date', props: { label: 'Due', value: '2026-09-30' } }),
  'bry-split': one('Two panes side by side.', { id: 'split', type: 'bry-split', props: { ratio: 40, label: 'Issues and detail' }, children: ['split-left', 'split-right'] }, [
    { id: 'split-left', type: 'bry-text', props: { text: 'The list' } },
    { id: 'split-right', type: 'bry-text', props: { text: 'The issue', tone: 'muted' } },
  ]),
  'bry-checkbox': one('A checked or unchecked value.', { id: 'checkbox', type: 'bry-checkbox', props: { label: 'Notify the reporter', checked: true } }),
  'bry-switch': one('A setting that is on or off.', { id: 'switch', type: 'bry-switch', props: { label: 'Closed issues', checked: false } }),
  'bry-board': one('Columns containing cards.', { id: 'board', type: 'bry-board', props: { label: 'Issues', cardSize: 'sm' }, children: ['todo-column', 'doing-column'] }, [
    { id: 'todo-column', type: 'bry-board-column', props: { title: 'To do' }, children: ['board-card'] },
    { id: 'doing-column', type: 'bry-board-column', props: { title: 'Doing', limit: 3 } },
    { id: 'board-card', type: 'bry-card', props: { title: ISSUES[0], padding: '3' } },
  ]),
  'bry-board-column': one('One board column.', { id: 'board-column', type: 'bry-board-column', props: { title: 'Doing', limit: 5 }, children: ['column-card'] }, [
    { id: 'column-card', type: 'bry-card', props: { title: ISSUES[1], padding: '3' } },
  ]),
  'bry-markdown': one('Formatted message text.', { id: 'markdown', type: 'bry-markdown', props: { text: '## Steps\n\n1. Open **Settings**\n2. Press `Save`' } }),
  'bry-diff': one('A pull request change.', { id: 'diff', type: 'bry-diff', props: { label: 'Changes', files: [{ path: 'src/auth.ts', status: 'modified', patch: '@@ -10,3 +10,4 @@\n   const user = await find(email);\n-  if (!user) return null;\n+  if (!user) throw new NotFound();\n   return user;\n' }] } }),
  'bry-file-grid': one('Files presented as tiles.', { id: 'file-grid', type: 'bry-file-grid', props: { label: 'Design files', count: 2, start: 0, tileSize: 'sm', files: [{ id: 'brief', name: 'Brief.docx', kind: 'document', size: 48200, modified: '2026-09-10T09:00:00Z' }, { id: 'budget', name: 'Budget.xlsx', kind: 'spreadsheet', size: 18400 }] } }),
  // ADR-A23 (catalogue-b)
  'bry-button-group': one('Buttons that belong together, drawn joined.', { id: 'button-group', type: 'bry-button-group', props: { label: 'Issue actions' }, children: ['group-open', 'group-close'] }, [
    { id: 'group-open', type: 'bry-button', props: { label: 'Reopen', variant: 'secondary', size: 'sm' } },
    { id: 'group-close', type: 'bry-button', props: { label: 'Close', variant: 'secondary', size: 'sm' } },
  ]),
  'bry-calendar': one('A month always open: one day, many, or a range.', { id: 'calendar', type: 'bry-calendar', props: { label: 'Leave', mode: 'range', values: ['2026-09-14', '2026-09-18'], month: '2026-09-01' } }),
  'bry-combobox': one('One choice from a long list, with a search.', { id: 'combobox', type: 'bry-combobox', props: { label: 'Assignee', placeholder: 'Pick a person', search: 'Search people', empty: 'Nobody matches.', value: 'ada', options: [{ value: 'ada', label: 'Ada Lovelace' }, { value: 'grace', label: 'Grace Hopper' }, { value: 'katherine', label: 'Katherine Johnson' }] } }),
  'bry-command': one('A search box over things to do.', { id: 'command', type: 'bry-command', props: { label: 'Commands', placeholder: 'Type a command', empty: 'No commands match.', items: [{ id: 'new', label: 'New issue', group: 'Issues', icon: 'add' }, { id: 'assign', label: 'Assign to me', group: 'Issues', icon: 'members' }, { id: 'archive', label: 'Archive closed issues', group: 'Tidy', icon: 'archive', hint: '12' }] } }),
  'bry-context-menu': one('Actions a right-click opens on its child.', { id: 'context-menu', type: 'bry-context-menu', props: { items: [{ id: 'copy', label: 'Copy link', icon: 'copy' }, { id: 'delete', label: 'Delete', tone: 'danger', separator: true }] }, children: ['context-card'] }, [
    { id: 'context-card', type: 'bry-card', props: { title: ISSUES[0], padding: '3' } },
  ]),
  'bry-data-table': one('A table the person sorts, filters, pages and chooses in.', { id: 'data-table', type: 'bry-data-table', props: { label: 'Issues', placeholder: 'Filter issues', perPage: 2, selectable: true, columns: [{ key: 'title', heading: 'Title', sortable: true, hideable: false }, { key: 'status', heading: 'Status', sortable: true }, { key: 'age', heading: 'Age', align: 'end' }], rows: [{ id: '1', cells: [ISSUES[0], 'To do', '2d'] }, { id: '2', cells: [ISSUES[1], 'Doing', '5d'] }, { id: '3', cells: [ISSUES[2], 'Done', '9d'] }] } }),
  'bry-field': one('A control with its name, description and error.', { id: 'field', type: 'bry-field', props: { label: 'Title', description: 'A short line people will search for.', required: true }, children: ['field-input'] }, [
    { id: 'field-input', type: 'bry-input', props: { placeholder: 'What went wrong?' } },
  ]),
  'bry-input-group': one('A field with an icon, a prefix, a suffix or a button.', { id: 'input-group', type: 'bry-input-group', props: { label: 'Site', prefix: 'https://', suffix: '.com', action: 'Check' } }),
  'bry-input-otp': one('A one-time code in a row of boxes.', { id: 'input-otp', type: 'bry-input-otp', props: { label: 'Code', length: 6, value: '123' } }),
  'bry-menubar': one('Menus over one part of the screen.', { id: 'menubar', type: 'bry-menubar', props: { label: 'Editor', menus: [{ id: 'file', label: 'File', items: [{ id: 'new', label: 'New note', icon: 'add' }, { id: 'archive', label: 'Archive', icon: 'archive' }] }, { id: 'edit', label: 'Edit', items: [{ id: 'copy', label: 'Copy', icon: 'copy' }] }] } }),
  'bry-native-select': one("One choice from the system's own list.", { id: 'native-select', type: 'bry-native-select', props: { label: 'Priority', value: 'high', options: [{ value: 'low', label: 'Low' }, { value: 'high', label: 'High' }, { value: 'urgent', label: 'Urgent' }] } }),
  'bry-section-menu': one('The sections of this screen, some with entries.', { id: 'section-menu', type: 'bry-section-menu', props: { label: 'Report sections', current: 'summary', sections: [{ id: 'summary', label: 'Summary' }, { id: 'teams', label: 'Teams', entries: [{ id: 'design', label: 'Design', description: 'Four people, nine issues' }, { id: 'platform', label: 'Platform', description: 'Six people, twelve issues' }] }] } }),
  'bry-pagination': one('Which page shows, and a way to the others.', { id: 'pagination', type: 'bry-pagination', props: { label: 'Issue pages', page: 3, count: 9 } }),
  'bry-questionnaire': one('Questions one at a time, sent together.', { id: 'questionnaire', type: 'bry-questionnaire', props: { title: 'How did the release go?', action: 'Send', questions: [{ id: 'mood', kind: 'rating', prompt: 'How smooth was it?', scale: 5, required: true }, { id: 'areas', kind: 'multiple', prompt: 'What slowed you down?', choices: [{ value: 'review', label: 'Review' }, { value: 'tests', label: 'Tests' }] }, { id: 'notes', kind: 'text', prompt: 'Anything else?', placeholder: 'Optional' }] } }),
  'bry-radio-group': one('One choice with every choice in view.', { id: 'radio-group', type: 'bry-radio-group', props: { label: 'Notify', value: 'mentions', options: [{ value: 'all', label: 'Everything' }, { value: 'mentions', label: 'Mentions only' }, { value: 'none', label: 'Nothing' }] } }),
  'bry-slider': one('A number along a line.', { id: 'slider', type: 'bry-slider', props: { label: 'Estimate, in hours', value: 6, min: 0, max: 40, step: 1 } }),
  'bry-toggle': one('A button that stays pressed.', { id: 'toggle', type: 'bry-toggle', props: { label: 'Show closed', pressed: true, icon: 'check' } }),
  'bry-toggle-group': one('Toggles side by side, one or many pressed.', { id: 'toggle-group', type: 'bry-toggle-group', props: { label: 'View', type: 'single', values: ['board'], items: [{ value: 'board', label: 'Board' }, { value: 'list', label: 'List' }, { value: 'calendar', label: 'Calendar', icon: 'calendar' }] } }),
  // ADR-A23 (catalogue-a)
  'bry-accordion': one("Sections that open and close under their headings.", {"id":"accordion","type":"bry-accordion","props":{"sections":[{"id":"steps","title":"Steps to reproduce"},{"id":"logs","title":"Logs"}],"expanded":["steps"]},"children":["accordion-steps","accordion-logs"]}, [{"id":"accordion-steps","type":"bry-text","props":{"text":"Open Settings, then press Save twice."}},{"id":"accordion-logs","type":"bry-text","props":{"text":"No logs attached.","tone":"muted"}}]),
  'bry-alert': one("A note that stays on the screen, in one of five tones with the tone's icon; children (a button that fixes it) sit under the words.", {"id":"alerts","type":"bry-stack","props":{"gap":"2"},"children":["alert-info","alert-warn"]}, [{"id":"alert-info","type":"bry-alert","props":{"title":"Sync is on","description":"Issues update as teammates change them."}},{"id":"alert-warn","type":"bry-alert","props":{"title":"Two issues have no owner","tone":"warn"}}]),
  'bry-alert-dialog': one('A yes-or-no that must be answered: Cancel and one action, and the backdrop does not close it.', { id: 'alert-dialog', type: 'bry-alert-dialog', props: { open: false, title: 'Delete this issue?', description: 'Its comments go with it.', action: 'Delete', tone: 'danger' } }),
  'bry-aspect-ratio': one("Holds its children to one named shape (16:9, 1:1, …) whatever the width.", {"id":"ratio","type":"bry-aspect-ratio","props":{"ratio":"16:9"},"children":["ratio-card"]}, [{"id":"ratio-card","type":"bry-card","props":{"title":"Preview","padding":"4"}}]),
  'bry-attachment': one("A file with a message, as a chip: its kind's icon, name and size (`bytes`).", {"id":"attachments","type":"bry-stack","props":{"direction":"row","gap":"2","wrap":true},"children":["att-1","att-2"]}, [{"id":"att-1","type":"bry-attachment","props":{"name":"Brief.docx","kind":"document","bytes":48200,"pressable":true}},{"id":"att-2","type":"bry-attachment","props":{"name":"crash.log","kind":"code","bytes":912,"removable":true}}]),
  'bry-breadcrumb': one("Where this screen is, from the top; pressing an earlier step raises `select` with its id.", {"id":"breadcrumb","type":"bry-breadcrumb","props":{"items":[{"id":"all","label":"All issues"},{"id":"web","label":"Web"},{"id":"iss_1","label":"Crash on save"}]}}),
  'bry-bubble': one("One said thing in Brydio's chat bubble: `from: self` is the person's own, at the end; `other` is anyone else's.", {"id":"bubbles","type":"bry-stack","props":{"gap":"2"},"children":["bubble-1","bubble-2"]}, [{"id":"bubble-1","type":"bry-bubble","props":{"text":"Is the crash on save fixed?"}},{"id":"bubble-2","type":"bry-bubble","props":{"text":"Yes, it shipped this morning.","from":"self"}}]),
  'bry-carousel': one("Its children as slides, one at a time, with Previous and Next; `index` is the slide shown and moving raises `change`.", {"id":"carousel","type":"bry-carousel","props":{"label":"Screenshots","index":0},"children":["slide-1","slide-2","slide-3"]}, [{"id":"slide-1","type":"bry-card","props":{"title":"Before","padding":"4"}},{"id":"slide-2","type":"bry-card","props":{"title":"During","padding":"4"}},{"id":"slide-3","type":"bry-card","props":{"title":"After","padding":"4"}}]),
  'bry-chart': one("Numbers as a bar, line, area or pie chart, in the kit's chart colours (never chosen by the app).", {"id":"chart","type":"bry-chart","props":{"kind":"bar","label":"Issues opened and closed by week","categories":["W36","W37","W38","W39"],"series":[{"name":"Opened","values":[12,9,14,7]},{"name":"Closed","values":[8,11,10,12]}]}}),
  'bry-collapsible': one("One section shown or hidden under a button bearing its title; pressing it raises `change` with `{ open }`.", {"id":"collapsible","type":"bry-collapsible","props":{"title":"Details","open":true},"children":["collapsible-text"]}, [{"id":"collapsible-text","type":"bry-text","props":{"text":"Reported on 12 September by Ada."}}]),
  'bry-direction': one("Its children read left to right or right to left, whatever the page reads.", {"id":"direction","type":"bry-direction","props":{"dir":"rtl"},"children":["direction-row"]}, [{"id":"direction-row","type":"bry-stack","props":{"direction":"row","gap":"2"},"children":["direction-a","direction-b"]},{"id":"direction-a","type":"bry-badge","props":{"text":"First"}},{"id":"direction-b","type":"bry-badge","props":{"text":"Second","tone":"brand"}}]),
  'bry-drawer': one('A panel that rises from the bottom for a short task.', { id: 'drawer', type: 'bry-drawer', props: { open: false, title: 'Quick filters' }, children: ['drawer-switch'] }, [{ id: 'drawer-switch', type: 'bry-switch', props: { label: 'Only mine' } }]),
  'bry-hover-card': one("A preview shown while the pointer rests on, or the focus is in, its first child; the rest of its children are the preview.", {"id":"hover","type":"bry-hover-card","props":{},"children":["hover-anchor","hover-text"]}, [{"id":"hover-anchor","type":"bry-button","props":{"label":"Ada Lovelace","variant":"ghost","size":"sm"}},{"id":"hover-text","type":"bry-text","props":{"text":"Owns 4 open issues."}}]),
  'bry-item': one("One thing that stands on its own (a setting, a linked account, a file to act on): an icon, a title and a line, with its children as actions at the end.", {"id":"items","type":"bry-stack","props":{"gap":"2"},"children":["item-1","item-2"]}, [{"id":"item-1","type":"bry-item","props":{"title":"Email updates","description":"A summary every morning.","icon":"mail","variant":"outline"},"children":["item-1-switch"]},{"id":"item-1-switch","type":"bry-switch","props":{"label":"Email updates","checked":true}},{"id":"item-2","type":"bry-item","props":{"loading":true}}]),
  'bry-kbd': one("A key or shortcut as a keycap: `mod+k` is ⌘K on a Mac and Ctrl+K elsewhere.", {"id":"kbd-row","type":"bry-stack","props":{"direction":"row","gap":"2","align":"center"},"children":["kbd-text","kbd"]}, [{"id":"kbd-text","type":"bry-text","props":{"text":"Search","size":"sm","tone":"muted"}},{"id":"kbd","type":"bry-kbd","props":{"text":"mod+k"}}]),
  'bry-marker': one("A mark across a thread or timeline, like \"Today\" or \"New messages\".", {"id":"marker","type":"bry-marker","props":{"text":"New messages","tone":"brand"}}),
  'bry-message': one("One message in a thread: who, their initials, when (`meta`), and its children; `from: self` sits at the end.", {"id":"message","type":"bry-message","props":{"name":"Grace Hopper","meta":"09:41"},"children":["message-bubble"]}, [{"id":"message-bubble","type":"bry-bubble","props":{"text":"Found it: the save runs twice."}}]),
  'bry-message-scroller': one("A thread's messages, oldest first, kept scrolled to the newest while the person is at the bottom; `more` asks for older ones at the top.", {"id":"scroller","type":"bry-message-scroller","props":{"label":"Thread"},"children":["scroller-today","scroller-1","scroller-2"]}, [{"id":"scroller-today","type":"bry-marker","props":{"text":"Today"}},{"id":"scroller-1","type":"bry-message","props":{"name":"Ada Lovelace","meta":"09:40"},"children":["scroller-1-bubble"]},{"id":"scroller-1-bubble","type":"bry-bubble","props":{"text":"Can you look at the crash?"}},{"id":"scroller-2","type":"bry-message","props":{"name":"You","meta":"09:41","from":"self"},"children":["scroller-2-bubble"]},{"id":"scroller-2-bubble","type":"bry-bubble","props":{"text":"On it.","from":"self"}}]),
  'bry-popover': one("A small panel opened from its first child; the rest of its children are the panel.", {"id":"popover","type":"bry-popover","props":{"title":"Snooze"},"children":["popover-anchor","popover-date"]}, [{"id":"popover-anchor","type":"bry-button","props":{"label":"Snooze","variant":"secondary","size":"sm"}},{"id":"popover-date","type":"bry-date","props":{"label":"Until"}}]),
  'bry-progress': one("How far along something is, as a percentage bar; without `value` it says only that it is under way.", {"id":"progress","type":"bry-progress","props":{"label":"Import","value":60}}),
  'bry-scroll-area': one("Its children in a region that scrolls on its own, up to a named `size`, with the shell's thin scrollbar.", {"id":"scroll","type":"bry-scroll-area","props":{"label":"Activity","size":"sm"},"children":["scroll-1","scroll-2","scroll-3"]}, [{"id":"scroll-1","type":"bry-list-row","props":{"title":"Crash on save"}},{"id":"scroll-2","type":"bry-list-row","props":{"title":"Search ignores accents"}},{"id":"scroll-3","type":"bry-list-row","props":{"title":"Dark mode flickers"}}]),
  'bry-separator': one("A hairline between groups, across or down.", {"id":"separated","type":"bry-stack","props":{"gap":"3"},"children":["sep-a","sep","sep-b"]}, [{"id":"sep-a","type":"bry-text","props":{"text":"Open"}},{"id":"sep","type":"bry-separator","props":{}},{"id":"sep-b","type":"bry-text","props":{"text":"Closed","tone":"muted"}}]),
  'bry-sheet': one('A panel that slides in from the side for detail or a longer form.', { id: 'sheet', type: 'bry-sheet', props: { open: false, title: 'Crash on save', description: 'Opened by Ada' }, children: ['sheet-text'] }, [{ id: 'sheet-text', type: 'bry-text', props: { text: 'Saving twice loses the second edit.' } }]),
  'bry-spinner': one("Something is under way, as a small spinner; for a region still loading use its own `loading`.", {"id":"spinner-row","type":"bry-stack","props":{"direction":"row","gap":"2","align":"center"},"children":["spinner","spinner-text"]}, [{"id":"spinner","type":"bry-spinner","props":{"label":"Syncing"}},{"id":"spinner-text","type":"bry-text","props":{"text":"Syncing…","size":"sm","tone":"muted"}}]),
  'bry-tabs': one("Views of one thing, one at a time: `tabs` names them and the n-th child is the n-th tab's panel; choosing one raises `change` with its id.", {"id":"tabs","type":"bry-tabs","props":{"label":"Issue","tabs":[{"id":"details","label":"Details"},{"id":"activity","label":"Activity"}],"value":"details"},"children":["tab-details","tab-activity"]}, [{"id":"tab-details","type":"bry-text","props":{"text":"Saving twice loses the second edit."}},{"id":"tab-activity","type":"bry-text","props":{"text":"Ada opened this.","tone":"muted"}}]),
  'bry-tooltip': one("A short hint over its child on hover and focus.", {"id":"tooltip","type":"bry-tooltip","props":{"text":"Archive this issue"},"children":["tooltip-button"]}, [{"id":"tooltip-button","type":"bry-button","props":{"label":"Archive","variant":"ghost","icon":"archive","hideLabel":true}}]),
  // Plan fidelity
  'bry-glyph': one("The mark before a work item's state or priority: a ring per state group, bars per priority.", {"id":"glyphs","type":"bry-stack","props":{"direction":"row","gap":"2","align":"center"},"children":["glyph-state","glyph-priority"]}, [{"id":"glyph-state","type":"bry-glyph","props":{"kind":"state","group":"started","label":"In progress"}},{"id":"glyph-priority","type":"bry-glyph","props":{"kind":"priority","priority":"high","label":"High priority"}}]),
  'bry-property': one("A work item's property as a small chip that opens its own picker: state, priority, people, labels, a date or a choice.", {"id":"props","type":"bry-stack","props":{"direction":"row","gap":"1","align":"center"},"children":["prop-state","prop-priority","prop-members","prop-due"]}, [{"id":"prop-state","type":"bry-property","props":{"kind":"state","label":"State","value":"doing","options":[{"value":"todo","label":"Todo","group":"unstarted"},{"value":"doing","label":"In Progress","group":"started","tone":"warn"},{"value":"done","label":"Done","group":"completed","tone":"success"}]}},{"id":"prop-priority","type":"bry-property","props":{"kind":"priority","display":"badge","label":"Priority","value":"high"}},{"id":"prop-members","type":"bry-property","props":{"kind":"members","label":"Assignees","values":["ada"],"options":[{"value":"ada","label":"Ada Lovelace"},{"value":"grace","label":"Grace Hopper"}]}},{"id":"prop-due","type":"bry-property","props":{"kind":"date","label":"Due date","value":"2026-10-02","due":true,"clearable":true}}]),
  'bry-quick-add': one("\"+ New work item\" that becomes a bare input where it sits: Enter saves, Escape cancels.", {"id":"quick-add","type":"bry-quick-add","props":{"trigger":"New work item","placeholder":"Issue title…","hint":"Enter to save · Esc to cancel"}}, []),
  'bry-work-card': one("One work item on a planning board: title, labels, priority, identifier, due date and assignees.", {"id":"work-card","type":"bry-work-card","props":{"title":"Search ignores accents","identifier":"WEB-14","priority":"high","labels":[{"label":"Bug","tone":"danger"},{"label":"Search","tone":"brand"}],"assignees":[{"id":"ada","name":"Ada Lovelace"}],"due":"2026-10-02","menu":[{"id":"archive","label":"Archive","icon":"archive"}]}}, []),
  'bry-page-header': one("The thin bar across the top of a page: breadcrumb, icon, title, count and the page's actions.", {"id":"page-header","type":"bry-page-header","props":{"title":"Issues","icon":"listLayout","count":24,"crumbs":[{"id":"project","label":"Website","initial":true}]},"children":["page-header-add"]}, [{"id":"page-header-add","type":"bry-button","props":{"label":"Add Issue","icon":"add","variant":"primary"}}]),
  'bry-entity-row': one("A sprint, module, saved view or request in a list: status mark or ring, title, dates, a status badge and metrics.", {"id":"entity-row","type":"bry-entity-row","props":{"title":"Sprint 12","dateRange":"Sep 22 – Oct 5","status":"active","statusLabel":"In progress","metrics":[{"label":"Progress","value":"42%","ring":42},{"label":"Scope","value":"18"}],"rail":{"month":"Sep","day":"22","active":true},"highlighted":true,"pressable":true}}, []),
  'bry-filter-menu': one("A Filter button whose menu lists facets, each opening options to tick, marked with their state or priority.", {"id":"filter-menu","type":"bry-filter-menu","props":{"facets":[{"id":"status","label":"Status","icon":"status","options":[{"value":"todo","label":"Todo","mark":"unstarted"},{"value":"in_progress","label":"In Progress","mark":"started","tone":"warn"},{"value":"done","label":"Done","mark":"completed","tone":"brand"}]},{"id":"priority","label":"Priority","icon":"flag","options":[{"value":"urgent","label":"Urgent","mark":"urgent"}]}],"values":[{"facet":"status","values":["todo"]}]}}, []),
  'bry-gantt': one("Work items along days: a bar from start to end, weekends shaded, a line at today; zoom by day, week or month.", {"id":"gantt","type":"bry-gantt","props":{"zoom":"week","showCompleted":false,"rows":[{"id":"web-12","title":"Crash on save","identifier":"WEB-12","mark":"started","priority":"urgent","assignee":"Ada Lovelace","start":"2026-09-21","end":"2026-10-02"},{"id":"web-14","title":"Search ignores accents","identifier":"WEB-14","mark":"unstarted","tone":"brand","priority":"high","assignee":"Grace Hopper","start":"2026-10-05","end":"2026-10-16"},{"id":"web-15","title":"Launch review","identifier":"WEB-15","mark":"backlog","priority":"medium","end":"2026-10-20"},{"id":"web-16","title":"Dark mode flickers","identifier":"WEB-16","mark":"unstarted","priority":"low","start":"2026-10-09","end":"2026-10-01"},{"id":"web-17","title":"Tidy the icons","identifier":"WEB-17","mark":"backlog","priority":"none"}]}}, []),
  'bry-timeline': one("A work item's activity, a line per change; an older block can fold into \"12 activities\" and raises `expand`.", {"id":"timeline","type":"bry-timeline","props":{"folded":false,"collapsedLabel":"3 activities"},"children":["activity-created","activity-status","activity-priority"]}, [{"id":"activity-created","type":"bry-timeline-item","props":{"actor":"Ada Lovelace","actorId":"ada","text":"created the issue","time":"2026-09-20T09:00:00Z"}},{"id":"activity-status","type":"bry-timeline-item","props":{"actor":"Ada Lovelace","actorId":"ada","text":"changed status to In Progress","mark":"status","tone":"warn","time":"2026-09-21T10:30:00Z"}},{"id":"activity-priority","type":"bry-timeline-item","props":{"actor":"Grace Hopper","actorId":"grace","text":"set priority to Urgent","mark":"priority","tone":"danger","time":"2026-09-22T14:00:00Z","count":3}}]),
  'bry-timeline-item': one("One line of activity: what changed, who changed it, how many times and how long ago.", {"id":"timeline-one","type":"bry-timeline","props":{},"children":["timeline-item"]}, [{"id":"timeline-item","type":"bry-timeline-item","props":{"actor":"Grace Hopper","actorId":"grace","text":"changed the due date to Oct 2","mark":"date","time":"2026-09-22T14:00:00Z","count":2}}]),
  'bry-comment': one("A comment in a thread: author, time, marks, the body as children, hover actions and a \"⋯\" menu; replies fold behind a bar.", {"id":"comment","type":"bry-comment","props":{"author":"Ada Lovelace","authorId":"ada","time":"2026-09-22T14:00:00Z","edited":true,"resolved":true,"replies":3,"collapsed":true,"repliers":[{"id":"grace","name":"Grace Hopper"},{"id":"linus","name":"Linus Torvalds"}],"actions":["reply","edit","resolve","copy","copyLink","subIssue","delete"]},"children":["comment-body","comment-reactions"]}, [{"id":"comment-body","type":"bry-markdown","props":{"text":"Saving twice loses the **second** edit. Repro in the attached file."}},{"id":"comment-reactions","type":"bry-reactions","props":{"items":[{"emoji":"👍","count":2,"mine":true}]}}]),
  'bry-page-tree': one("A wiki space's pages nested under pages: open a row for its subpages (sent when asked), drag to reorder or nest, a \"⋯\" menu and \"+\" per row.", {"id":"page-tree","type":"bry-page-tree","props":{"label":"Engineering","keep":"space-eng","selected":"p-rfc","draggable":true,"addable":true,"actions":["newChild","rename","duplicate","move","copyLink","delete"],"items":[{"id":"p-handbook","label":"Handbook","emoji":"📘","hasChildren":true},{"id":"p-onboarding","parent":"p-handbook","label":"Onboarding"},{"id":"p-rfc","parent":"p-handbook","label":"RFC: one editor schema"},{"id":"p-runbooks","label":"Runbooks","hasChildren":true},{"id":"p-release","label":"Release notes"}]}}, []),
  'bry-comment-margin': one("The threads on a co-edited text, each level with the words it is on (beside the text when wide, stacked when narrow).", {"id":"margin","type":"bry-comment-margin","props":{},"children":["margin-one","margin-two"]}, [{"id":"margin-one","type":"bry-comment","props":{"author":"Ada Lovelace","authorId":"ada","time":"2026-10-07T09:00:00Z","anchor":"c-1","quote":"ship on Friday","actions":["reply","resolve"]},"children":["margin-one-body"]},{"id":"margin-one-body","type":"bry-markdown","props":{"text":"Can we make Thursday? Release notes need a day."}},{"id":"margin-two","type":"bry-comment","props":{"author":"Grace Hopper","authorId":"grace","time":"2026-10-07T10:30:00Z","anchor":"c-2","quote":"two API servers","orphaned":true,"actions":["reply","resolve"]},"children":["margin-two-body"]},{"id":"margin-two-body","type":"bry-markdown","props":{"text":"One is enough for now (DW-Q1)."}}]),
  'bry-history': one("A co-edited record's versions by day with who wrote in each; preview, compare two (changes marked), name, restore or fork. Drawn by the host from the record it is bound to.", {"id":"history","type":"bry-history","props":{"bind":{"collection":"pages","id":"page_1"},"field":"body","forkable":true}}, []),
  'bry-reactions': one("Emoji reactions as round chips with counts, yours tinted, and a dashed button to add one; pressing raises `toggle`.", {"id":"reactions","type":"bry-reactions","props":{"items":[{"emoji":"👍","count":3,"mine":true},{"emoji":"🎉","count":1},{"emoji":"👀","count":2}]}}, []),
  'bry-peek': one("A floating panel over the side of a list that shows one item without leaving it, with previous and next.", {"id":"peek","type":"bry-peek","props":{"open":true,"label":"Issue WEB-12","position":"3 / 12","previous":true,"next":true},"children":["peek-title"]}, [{"id":"peek-title","type":"bry-heading","props":{"level":2,"text":"Search ignores accents"}}]),
  'bry-spreadsheet': one("A table whose cells are live elements, with pinned columns and per-column sort and hide.", {"id":"sheet","type":"bry-spreadsheet","props":{"label":"Issues","selectable":true,"total":1,"columns":[{"key":"title","heading":"Title","width":"fill","pinned":true,"sortable":true},{"key":"status","heading":"Status","width":"md","sortable":true,"hideable":true}]},"children":["sheet-group","sheet-row"]}, [{"id":"sheet-group","type":"bry-spreadsheet-group","props":{"label":"In Progress","mark":"started","tone":"warn","count":1}},{"id":"sheet-row","type":"bry-spreadsheet-row","props":{"label":"WEB-12"},"children":["sheet-title","sheet-status"]},{"id":"sheet-title","type":"bry-text","props":{"text":"Search ignores accents","variant":"ui"}},{"id":"sheet-status","type":"bry-badge","props":{"text":"In Progress","tone":"warn"}}]),
  'bry-spreadsheet-row': one("One row of a spreadsheet: its children are its cells.", {"id":"sheet-only-row","type":"bry-spreadsheet-row","props":{"label":"WEB-13","depth":1},"children":["sheet-only-cell"]}, [{"id":"sheet-only-cell","type":"bry-text","props":{"text":"Sub-issue"}}]),
  'bry-spreadsheet-group': one("A heading row between groups of a spreadsheet's rows, folded or open.", {"id":"sheet-only-group","type":"bry-spreadsheet-group","props":{"label":"Todo","mark":"unstarted","count":4}}, []),
  'bry-rich-text': one("A markdown editor that looks like the text it makes: headings, lists, tasks, code, links and @mentions.", {"id":"rich","type":"bry-rich-text","props":{"label":"Description","value":"## Steps\n\n- Open a draft\n- Go offline","mentions":[{"value":"ada","label":"Ada Lovelace"}]}}, []),
  'bry-whiteboard': one("An endless canvas several people draw on at once, bound to a record's drawing field.", {"id":"board","type":"bry-whiteboard","props":{"bind":{"collection":"boards","id":"board_1","field":"canvas"},"size":"sm","label":"Retro"}}, []),
  'bry-approval': one("One Brydio approval request: its steps and approvers, and Approve or Decline when the viewer may decide.", {"id":"approval","type":"bry-approval","props":{"request":"apr_1"}}, []),
  'bry-board-lane': one("One swimlane's heading on a lanes board: its person or status, title and count.", {"id":"lane","type":"bry-board-lane","props":{"title":"Ada Lovelace","mark":"person","count":5,"collapsible":true}}, []),
  'bry-property-list': one("A section of a detail sidebar: a folding title over label-and-value rows that line up.", {"id":"props-list","type":"bry-property-list","props":{"title":"Properties","collapsible":true},"children":["props-status"]}, [{"id":"props-status","type":"bry-property-row","props":{"label":"Status","icon":"status"},"children":["props-status-value"]},{"id":"props-status-value","type":"bry-badge","props":{"text":"In Progress","tone":"warn"}}]),
  'bry-property-row': one("One property in a detail sidebar: a muted label with its icon, and its value.", {"id":"prop-row","type":"bry-property-row","props":{"label":"Created","icon":"calendar","readonly":true},"children":["prop-row-value"]}, [{"id":"prop-row-value","type":"bry-text","props":{"text":"Sep 28","variant":"caption"}}]),
  'bry-keys': one("The keyboard shortcuts a screen answers while shown, as C to create and J or K to step. Draws nothing itself: the keycaps here are bry-kbd beside it.", {"id":"keys-demo","type":"bry-stack","props":{"gap":"2"},"children":["keys","keys-c","keys-j"]}, [{"id":"keys","type":"bry-keys","props":{"bindings":[{"key":"c","label":"Create an issue"},{"key":"j","label":"Next issue"}]}},{"id":"keys-c","type":"bry-stack","props":{"direction":"row","gap":"2","align":"center"},"children":["keys-c-kbd","keys-c-text"]},{"id":"keys-c-kbd","type":"bry-kbd","props":{"text":"c"}},{"id":"keys-c-text","type":"bry-text","props":{"text":"Create an issue"}},{"id":"keys-j","type":"bry-stack","props":{"direction":"row","gap":"2","align":"center"},"children":["keys-j-kbd","keys-j-text"]},{"id":"keys-j-kbd","type":"bry-kbd","props":{"text":"j"}},{"id":"keys-j-text","type":"bry-text","props":{"text":"Next issue"}}]),
  'bry-filter-chip': one("One filter in force: its facet, marks of what is chosen, a summary, and a cross to remove it.", {"id":"filter-chip","type":"bry-filter-chip","props":{"label":"Status","icon":"status","text":"2 statuses","marks":[{"mark":"unstarted"},{"mark":"started","tone":"warn"}]}}, []),
} satisfies Record<ElementName, ElementExample>;

function jsxValue(value: unknown): string {
  return `{${JSON.stringify(value)}}`;
}

export function jsxFor(example: ElementExample): string {
  const nodes = new Map(example.nodes.map(node => [node.id, node]));

  const render = (id: string, indent = ''): string => {
    const node = nodes.get(id);
    if (!node) return '';

    const props = Object.entries(node.props)
      .map(([name, value]) => ` ${name}=${jsxValue(value)}`)
      .join('');
    const children = node.children?.map(child => render(child, `${indent}  `)).filter(Boolean) ?? [];

    return children.length
      ? `${indent}<${node.type}${props}>\n${children.join('\n')}\n${indent}</${node.type}>`
      : `${indent}<${node.type}${props} />`;
  };

  return render(example.root);
}

export function exampleFingerprint(name: ElementName): string {
  return createHash('sha256').update(JSON.stringify(EXAMPLES[name])).digest('hex');
}
